cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
  path('', views.cart_detail, name='cart_detail'),
  path('add/<int:product_id>/', views.cart_add, name='cart_add'),
  path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('shop.urls', namespace='shop')),
    path('', include('orders.urls', namespace='orders')),

]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
  path('create/', views.order_create, name='order_create'),
]

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
  path('', views.HomeView.as_view(), name='homepage'),
  path('listall', views.ProductListView.as_view(), name='all_product_list'),
  path('brand/<slug:brand_slug>', views.BrandView.as_view(), name='product_list_by_brand'),
  path('category/<slug:category_slug>', views.CategoryView.as_view(), name='product_list_by_category'),
  path('<slug:product_category_slug>/<slug:product_brand_slug>/<slug:slug>/', views.ProductDetail.as_view(), name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]  # диапазон добавляемого количества товара


class CartAddProductForm(forms.Form):
  quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label='Количество товара')
  override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST

from cart.cart import Cart
from cart.forms import CartAddProductForm
from shop.models import Product


@require_POST
def cart_add(request, product_id):
  cart = Cart(request)
  product = get_object_or_404(Product, id=product_id)
  form = CartAddProductForm(request.POST)
  if form.is_valid():
    cd = form.cleaned_data
    cart.add(product=product, quantity=cd['quantity'], override_quantity=cd['override'])
  return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, product_id):
  cart = Cart(request)
  product = get_object_or_404(Product, id=product_id)
  cart.remove(product)
  return redirect('cart:cart_detail')

def cart_detail(request):
  cart = Cart(request)
  for item in cart:
    item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'override': True})
  return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %} Корзина {% endblock %}
{% block content %}
  <h1>Ваша корзина</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>Изображение</th>
        <th>Товар</th>
        <th>Количество</th>
        <th>Удалить</th>
        <th>Цена за 1 шт.</th>
        <th>Стоимость</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %} {{ product.image.url}}
                          {% else %}
                            {% static "assets/cream.jpg" %}
                          {% endif %}" alt="">
              </a>
            </td>
            <td>{{ product.product_name }}</td>
            <td>
              <form action="{% url "cart:cart_add" product.id %}" method="post">
                {{ item.update_quantity_form.quantity }} {{ item.update_quantity_form.override }}
                <input type="submit" value="Обновить">
                {% csrf_token %}
              </form>
            </td>
            <td>
              <form action="{% url "cart:cart_remove" product.id %}" method="post">
                <input type="submit" value="Удалить">
                {% csrf_token %}
              </form>
            </td>
            <td class="num">{{ item.price }} руб.</td>
            <td class="num">{{ item.total_price }} руб.</td>
          </tr>
        {% endwith %}
      {% endfor %}
      <tr class="total">
        <td colspan="5">Всего</td>
        <td class="num">{{ cart.get_total_price }} руб.</td>
      </tr>
    </tbody>
  </table>
  <p class="text-right">
    <a href="{% url "shop:all_product_list" %}" class="button-light">Продолжить покупки</a>
    <a href="{% url "orders:order_create" %}" class="button">Оплатить</a>
  </p>
{% endblock %}