cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
  path('', views.cart_detail, name='cart_detail'),
  path('add/<int:product_id>/', views.cart_add, name='cart_add'),
  path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('shop.urls', namespace='shop')),
    path('', include('orders.urls', namespace='orders')),

]

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
  path('', views.HomeView.as_view(), name='homepage'),
  path('listall', views.ProductListView.as_view(), name='all_product_list'),
  path('brand/<slug:brand_slug>', views.BrandView.as_view(), name='product_list_by_brand'),
  path('category/<slug:category_slug>', views.CategoryView.as_view(), name='product_list_by_category'),
  path('<slug:product_category_slug>/<slug:product_brand_slug>/<slug:slug>/', views.ProductDetail.as_view(), name='product_detail'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>{% block title %}Косметиста{% endblock title%}</title>
    <link href="{% static "css/base-min.css" %}" rel="stylesheet">
  </head>
  <body>
    <header id="main-header">
      <div id="logo">
        <a href="/" class="logo">Косметиста</a>
      </div>
      <div id="menu">
        <a href="{% url 'shop:all_product_list'%}">Все продукты</a>
      </div>
      <div id="user-header">
        {% if user.is_authenticated %}
            <p>Привет, {{ user.first_name }}!</p>
            <a href="{% url 'logout'%}">Выйти</a>
        {% else %}
            <p>Вы не вошли на сайт</p>
            <a href="{% url 'login' %}">Войти</a>
        {% endif %}
      </div>
      <div id="cart-header">
        <div class="cart">
          {% with total_items=cart|length %}
            {% if total_items > 0 %}
              Ваша корзина:
              <a href="{% url "cart:cart_detail" %}">
                Всего продуктов: {{ total_items }}, на сумму {{ cart.get_total_price }} руб.
              </a>
            {% else %} Корзина пустая.
            {% endif %}
          {% endwith %}
        </div>
      </div>
    </header>
    <main>
      {% block content %}
      {% endblock content%}
    </main>
  </body>
</html>

templates/search.html
<!DOCTYPE html>
{% extends './extensions/menu.html' %}
{% block content %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Заказы</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>
<body>
    {% if list_of_all_orders.count == 0 %}
        <h1>Не найдено</h1>
    {% else %}
        <h1>Список заказов для:</h1>
    <h2>{{ list_of_all_orders.0.customer }}</h2>
    <table>
        <tr>
            <th>Заказанный продукт</th>
            <th>Дата заказа</th>
        </tr>
        {% for order in list_of_all_orders %}
        <tr>
            <td>{{ order.product }}</td>
            <td>{{ order.order_date }}</td>
       </tr>
        {% endfor %}
    </table>
    {% endif %}

{% endblock content %}
</body>
<script src="{% static 'js/script.js' %}" ></script>
</html>